# Generated by Django 3.0.2 on 2020-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='average',
            field=models.BooleanField(default=True, verbose_name='Whether or not to use this in average'),
        ),
    ]
