# Generated by Django 3.0.6 on 2020-11-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('sensor', 'time')},
        ),
    ]
