# Generated by Django 3.0.6 on 2020-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201119_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date and time of status change')),
                ('good', models.BooleanField(verbose_name='Weather now good?')),
            ],
        ),
    ]
