# Generated by Django 2.2.4 on 2019-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_sensortype_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='class_name',
            field=models.CharField(max_length=100, verbose_name='Name of Python class to handle station'),
        ),
    ]
