# Generated by Django 2.2.4 on 2019-08-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190826_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='plot',
            field=models.BooleanField(default=True, verbose_name='Add station to plots'),
        ),
    ]
