# Generated by Django 4.2.2 on 2023-07-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_alter_evaluator_id_alter_goodweather_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluator",
            name="name",
            field=models.CharField(max_length=30, unique=True, verbose_name="Name of evaluator"),
        ),
    ]
