# Generated by Django 4.2.2 on 2023-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0005_alter_evaluator_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluator",
            name="name",
            field=models.CharField(max_length=15, unique=True, verbose_name="Name of evaluator"),
        ),
        migrations.AlterField(
            model_name="station",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Code for weather station"),
        ),
    ]
