# Generated by Django 2.2.4 on 2019-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_station_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='evaluators',
            field=models.ManyToManyField(blank=True, to='weather.Evaluator'),
        ),
    ]
