# Generated by Django 4.2.2 on 2023-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0006_alter_evaluator_name_alter_station_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Whether to use this sensor"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="average",
            field=models.BooleanField(default=True, verbose_name="Whether to use this in average"),
        ),
    ]
