# Generated by Django 2.2.4 on 2019-08-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20190826_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='good',
        ),
    ]
