# Generated by Django 2.2.4 on 2019-08-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_value_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='kwargs',
            field=models.CharField(default='{}', max_length=100, verbose_name='JSON encoded kwargs used when instantiating Python class'),
        ),
    ]
