# Generated by Django 5.2.15 on 2026-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_sensor_active_alter_sensor_average'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('station', 'type'), name='unique_sensor_station_type'),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(fields=('sensor', 'time'), name='unique_value_sensor_time'),
        ),
    ]
